### ISSUE TITLE
'net.ipv4.conf.default.rp_filter' not a valid key

### ISSUE THREAD

**Issue by ryayon** [hercules-team/augeasproviders_sysctl#23]
Hi,

On RHEL v6.9 with a puppet-agent v5.5.1, I get the following error:
**`Sysctl[net.ipv4.conf.default.rp_filter]: Could not evaluate: Error: 'net.ipv4.conf.default.rp_filter' is not a valid sysctl key`**

While if I run a **`sysctl -p`**, I don't get error for this specific entry:
```
# sysctl -p
...
net.ipv4.conf.default.rp_filter = 1
....
error: "net.bridge.bridge-nf-call-ip6tables" is an unknown key
error: "net.bridge.bridge-nf-call-iptables" is an unknown key
error: "net.bridge.bridge-nf-call-arptables" is an unknown key
```

Do you have any idea?

Regards

**Comment by trevor-vaughan** [comment]
@ryayon The `sysctl` type uses prefetching to list out all of the various parameters prior to application. Does this happen on every puppet run or just the first? You may have something in your puppet code that is adding the kernel module for `rp_filter` (network, iptables, etc...)

**Comment by ryayon** [comment]
Hi @trevor-vaughan ,

You are right.
I have 'net.bridge.bridge-nf-call-iptables=0' and 'net.bridge.bridge-nf-call-ip6tables=0' in another location.

Thank you

**Comment by shadyabhi** [comment]
Hi @trevor-vaughan, 

I stumbled upon this because I'm having the same issue. Is there a way to refresh our prefetched list in the middle of the puppet run?

**Comment by trevor-vaughan** [comment]
@shadyabhi Unfortunately, since there is no guarantee of order in puppet (and frankly, there's no way to know how you actually set the other resource it could be an `exec`, custom type, `package`, etc...), doing a refresh in the middle of the run wouldn't do much good in general and would just give you a possible solution, not an actual solution.

If you know what is doing the loading, you can check things explicitly. Otherwise, you simply have to have a two-pass convergence.

**Comment by shadyabhi** [comment]
@trevor-vaughan, running puppet 2 times is definitely not what we should have as a workaround if that's what you meant by 2-pass convergence. 

In terms of prefetching, I was hoping if it would make sense to disable prefetching via an option. For now, I had to move to a different module which wasn't prefetching the values. (not something I wanted but had to move because of my requirement). 

Isn't it a valid use-case where Puppet is doing some things that creates new sysctl paths and puppet should definitely have a way to set these new sysctl values when proper ordering is defined in manifests. I also noticed that prefetching was added as a feature in one of the newer versions which breaks the use-cases where puppet adds new sysctl values during the run. 

What are your thoughts? I don't see a reason why the module shouldn't be flexible enough to incorporate this use-case.

**Comment by raphink** [comment]
@shadyabhi prefetching is a provider-level action, not a resource-level one, as it happens before any resource gets applied. The Puppet DSL allows to manipulate resources, not providers, so there is no clean way to pass parameters to the provider through the language.

**Comment by raphink** [comment]
Now if the problem is that the provider is not properly parsing valid keys, the best approach is to fix the provider to parse them properly…

**Comment by shadyabhi** [comment]
@raphink Thanks for replying. The issue is that the new sysctl values are set during the puppet run so this module has a limitation where I can't set the "newly created" sysctl values. I wondering what approach should be used to get around this limitation.
